# Generated by Django 5.1.7 on 2025-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMDB_Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('backdrop_path', models.CharField(
                    blank=True, max_length=500, null=True)),
                ('poster_path', models.CharField(
                    blank=True, max_length=500, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('overview', models.TextField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('character', models.TextField()),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
