# Generated by Django 5.1.7 on 2025-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMDB_Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vote_count', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=255)),
                ('budget', models.BigIntegerField()),
                ('homepage', models.URLField()),
                ('imdb_id', models.CharField(max_length=15)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poster_path', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('production_companies', models.CharField(max_length=255)),
                ('production_countries', models.CharField(max_length=255)),
                ('spoken_languages', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
